In [13]:
import numpy as np
import pandas as pd

In [46]:
corr = np.random.rand(100,100)
x = np.arange(10)
y = np.arange(1,11)

In [53]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
print(corr[0,1],corr[1,2])

0.6330315102553766 0.06470007724064242


In [55]:
corr[x,y]

array([0.63303151, 0.06470008, 0.58291947, 0.84868459, 0.53061158,
       0.51309139, 0.07826821, 0.12935572, 0.95158615, 0.64157274])

array([0.63303151, 0.06470008, 0.58291947, 0.84868459, 0.53061158,
       0.51309139, 0.07826821, 0.12935572, 0.95158615, 0.64157274])

In [39]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
np.take(corr,[x,y]).T

array([[0.70162612, 0.24585622],
       [0.24585622, 0.96092332],
       [0.96092332, 0.1436273 ],
       [0.1436273 , 0.90633877],
       [0.90633877, 0.05703238],
       [0.05703238, 0.22270719],
       [0.22270719, 0.10887609],
       [0.10887609, 0.69631956],
       [0.69631956, 0.59771358],
       [0.59771358, 0.93479322]])

In [36]:
corr

array([[0.70162612, 0.24585622, 0.96092332, 0.1436273 , 0.90633877,
        0.05703238, 0.22270719, 0.10887609, 0.69631956, 0.59771358],
       [0.93479322, 0.5747711 , 0.07045811, 0.25295692, 0.56396296,
        0.90577833, 0.62041782, 0.30935442, 0.93104273, 0.54281431],
       [0.74457437, 0.39952463, 0.61805911, 0.41736057, 0.17186194,
        0.57215684, 0.89717387, 0.71309923, 0.434164  , 0.02248955],
       [0.59682363, 0.95240724, 0.4837095 , 0.75319937, 0.65917391,
        0.90040569, 0.83043314, 0.64920344, 0.5227467 , 0.3309544 ],
       [0.78786702, 0.12179591, 0.6153591 , 0.74489296, 0.36062063,
        0.81818091, 0.40956625, 0.41672637, 0.30183699, 0.9622575 ],
       [0.91892145, 0.2624197 , 0.52399626, 0.80330632, 0.17407355,
        0.72683083, 0.54823097, 0.92568707, 0.19589795, 0.30948484],
       [0.33402635, 0.0083915 , 0.7226777 , 0.64141496, 0.82926744,
        0.27666462, 0.66466452, 0.44901266, 0.8400802 , 0.21496102],
       [0.60802992, 0.79168193, 0.6893574